authors:
  dooms:
    name: Dooms
    description: Hat master
    avatar: https://github.com/Doomsk.png
  qinho:
    name: Inho
    description: _in progress_
    avatar: https://github.com/q-inho.png


