[package]
name = "hhat_lang"
version = "0.3.0-alpha.1"
edition = "2024"

[workspace]
members = ["hhat_core", "hhat_dialects/hhat_heather"]

[dependencies]
peg = "0.8.5"
walkdir = "2.5.0"
itertools = "0.14.0"
cranelift = "0.128.3"
cranelift-module = "0.128.3"
cranelift-jit = "0.128.3"
strum = "0.28.0"
toml = { version = "1.1.2", features = ["preserve_order", "serde"] }
serde = { version = "1.0.228", features = ["derive"] }
