"""
Update current files; It can be to create respective doc files for
the existing files.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from hhat_lang.toolchain.project import DOCS_FOLDER_NAME, SOURCE_FOLDER_NAME
from hhat_lang.toolchain.project.utils import get_proj_dir, str_to_path

SECTION_PATTERN = re.compile(r"(?ms)^## (?P<name>[^\n]+)\n(?P<body>.*?)(?=^## |\Z)")
FUNCTION_PATTERN = re.compile(
    r"(?ms)(?:^|(?<=[\s{}]))fn\s+"
    r"(?P<name>@?[A-Za-z_][A-Za-z0-9_-]*)\s*"
    r"\((?P<args>[^)]*)\)\s*"
    r"(?P<return_type>[^\s{]+)?\s*\{"
)
TYPE_PATTERN = re.compile(
    r"(?ms)(?:^|(?<=[\s{}]))type\s+"
    r"(?P<name>@?[A-Za-z_][A-Za-z0-9_-]*)\s*"
    r"(?:(?::\s*(?P<alias>[^\s{]+))|\{(?P<body>.*?)\})"
)
ARG_PATTERN = re.compile(r"(?P<name>@?[A-Za-z_][A-Za-z0-9_-]*)\s*:\s*(?P<type>[^\s{}]+)")
GENERATED_MARKER = "<!-- Generated by hat update; edit Documentation sections only. -->"


@dataclass(frozen=True)
class Argument:
    name: str
    type: str


@dataclass(frozen=True)
class Signature:
    name: str
    kind: str
    type: str
    paradigm: str
    arguments: tuple[Argument, ...] = ()
    members: tuple[Argument, ...] = ()
    variants: tuple[str, ...] = ()


def update_project(project_name: str | Path | None = None) -> dict[str, int]:
    """Create and synchronize markdown docs for a H-hat project.

    The update command mirrors ``src/**/*.hat`` files under ``docs/**/*.md`` and
    rewrites generated signature blocks while preserving prose below each
    ``### Documentation`` heading.
    """
    project_path = get_proj_dir(str_to_path(project_name)) if project_name else get_proj_dir()
    docs_path = project_path / DOCS_FOLDER_NAME
    docs_path.mkdir(parents=True, exist_ok=True)

    source_files = sorted((project_path / SOURCE_FOLDER_NAME).rglob("*.hat"))
    written = 0
    for source_file in source_files:
        doc_file = _doc_path_for_source(project_path, source_file)
        signatures = _parse_signatures(source_file.read_text())
        content = _render_doc_file(doc_file, source_file, signatures)
        doc_file.parent.mkdir(parents=True, exist_ok=True)
        if not doc_file.exists() or doc_file.read_text() != content:
            doc_file.write_text(content)
            written += 1

    removed = _remove_orphan_docs(project_path, source_files)
    return {"source_files": len(source_files), "docs_written": written, "docs_removed": removed}


def _doc_path_for_source(project_path: Path, source_file: Path) -> Path:
    source_root = project_path / SOURCE_FOLDER_NAME
    relative_source = source_file.relative_to(source_root)
    return project_path / DOCS_FOLDER_NAME / relative_source.with_suffix(".md")


def _source_path_for_doc(project_path: Path, doc_file: Path) -> Path:
    docs_root = project_path / DOCS_FOLDER_NAME
    relative_doc = doc_file.relative_to(docs_root)
    return project_path / SOURCE_FOLDER_NAME / relative_doc.with_suffix(".hat")


def _parse_signatures(text: str) -> list[Signature]:
    text = _strip_comments(text)
    signatures: list[Signature] = []
    for match in FUNCTION_PATTERN.finditer(text):
        arguments = tuple(
            Argument(arg_match.group("name"), arg_match.group("type"))
            for arg_match in ARG_PATTERN.finditer(match.group("args"))
        )
        signatures.append(
            Signature(
                name=match.group("name"),
                kind="function",
                type=match.group("return_type") or "unit",
                paradigm=_paradigm_for_name(match.group("name")),
                arguments=arguments,
            )
        )

    for match in TYPE_PATTERN.finditer(text):
        alias = match.group("alias")
        body = match.group("body") or ""
        members = tuple(
            Argument(member_match.group("name"), member_match.group("type"))
            for member_match in ARG_PATTERN.finditer(body)
        )
        variants = tuple(
            variant
            for variant in re.findall(r"@?[A-Za-z_][A-Za-z0-9_-]*", body)
            if variant not in {member.name for member in members}
        )
        if alias:
            kind = "type alias"
            type_name = alias
        elif members:
            kind = "struct"
            type_name = match.group("name")
        else:
            kind = "enum"
            type_name = match.group("name")
        signatures.append(
            Signature(
                name=match.group("name"),
                kind=kind,
                type=type_name,
                paradigm=_paradigm_for_name(match.group("name")),
                members=members,
                variants=variants,
            )
        )

    return sorted(signatures, key=lambda signature: (signature.kind, signature.name))


def _strip_comments(text: str) -> str:
    text = re.sub(r"(?s)/\*.*?\*/", "", text)
    return re.sub(r"//.*", "", text)


def _paradigm_for_name(name: str) -> str:
    return "quantum" if name.startswith("@") else "classical"


def _render_doc_file(doc_file: Path, source_file: Path, signatures: Iterable[Signature]) -> str:
    existing = doc_file.read_text() if doc_file.exists() else ""
    intro, existing_sections = _split_existing_doc(existing)
    lines = [f"# {source_file.stem}", "", GENERATED_MARKER, ""]
    if intro:
        lines.extend([intro.rstrip(), ""])

    for signature in signatures:
        preserved_docs = existing_sections.get(signature.name, "")
        lines.extend(_render_signature(signature, preserved_docs))

    return "\n".join(lines).rstrip() + "\n"


def _split_existing_doc(text: str) -> tuple[str, dict[str, str]]:
    if not text.strip():
        return "", {}

    header_match = re.match(r"(?ms)^# [^\n]+\n(?P<intro>.*?)(?=^## |\Z)", text)
    intro = (header_match.group("intro") if header_match else "").strip()
    intro = intro.replace(GENERATED_MARKER, "").strip()
    sections: dict[str, str] = {}
    for match in SECTION_PATTERN.finditer(text):
        docs_match = re.search(r"(?ms)^### Documentation\s*\n(?P<docs>.*)", match.group("body"))
        if docs_match:
            sections[match.group("name").strip()] = docs_match.group("docs").strip()
    return intro, sections


def _render_signature(signature: Signature, preserved_docs: str) -> list[str]:
    lines = [
        f"## {signature.name}",
        "",
        "### Signature",
        "",
        f"- Name: {signature.name}",
        f"- Type: {signature.type}",
        f"- Kind: {signature.kind}",
        f"- Paradigm: {signature.paradigm}",
    ]

    if signature.arguments:
        lines.extend(
            ["- Arguments:", "", "  | Argument | Type | Paradigm |", "  | :--- | :--- | :--- |"]
        )
        for argument in signature.arguments:
            lines.append(
                f"  | {argument.name} | {argument.type} | {_paradigm_for_name(argument.name)} |"
            )
    elif signature.kind == "function":
        lines.append("- Arguments: none")

    if signature.members:
        lines.extend(
            ["- Members:", "", "  | Member | Type | Paradigm |", "  | :--- | :--- | :--- |"]
        )
        for member in signature.members:
            lines.append(f"  | {member.name} | {member.type} | {_paradigm_for_name(member.name)} |")

    if signature.variants:
        lines.extend(["- Variants:", ""])
        for variant in signature.variants:
            lines.append(f"  - {variant}")

    lines.extend(["", "### Documentation", ""])
    lines.append(preserved_docs if preserved_docs else "<!-- Add documentation here. -->")
    lines.append("")
    return lines


def _remove_orphan_docs(project_path: Path, source_files: Iterable[Path]) -> int:
    source_set = {source_file.resolve() for source_file in source_files}
    removed = 0
    docs_root = project_path / DOCS_FOLDER_NAME
    if not docs_root.exists():
        return removed

    for doc_file in sorted(docs_root.rglob("*.md")):
        source_file = _source_path_for_doc(project_path, doc_file)
        doc_text = doc_file.read_text()
        if source_file.resolve() not in source_set and (
            GENERATED_MARKER in doc_text or not doc_text.strip()
        ):
            doc_file.unlink()
            removed += 1
    return removed
