repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        files: ^python/
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        files: ^python/src/hhat_lang/(toolchain|dialects/heather/grammar/doc_signatures\.py)
        args: [
          --ignore-missing-imports,
          --disable-error-code, attr-defined,
          --disable-error-code, override,
          --disable-error-code, misc,
        ]
        exclude: tests
        additional_dependencies: [tokenize-rt==3.2.0]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.9"
    hooks:
      - id: ruff-check
        files: ^python/(src/hhat_lang/(toolchain|dialects/heather/grammar/doc_signatures\.py)|tests/test_cli\.py$)
        args: [--fix, --show-fixes, --show-files]
      - id: ruff-format
        files: ^python/(src/hhat_lang/(toolchain|dialects/heather/grammar/doc_signatures\.py)|tests/test_cli\.py$)
        args: [--line-length=100]

default_language_version:
  python: python3.12
