from __future__ import annotations

from pathlib import Path

from hhat_lang.toolchain.project.new import (
    create_new_fn_file,
    create_new_project,
    create_new_type_file,
)
from hhat_lang.toolchain.project.update import update_project


def test_update_project_creates_docs_and_preserves_user_documentation(tmp_path: Path) -> None:
    project = tmp_path / "demo"
    create_new_project(project)
    source_file = project / "src" / "math.hat"
    source_file.write_text(
        """
fn sum(a:i64 b:i64) i64 { ::add(a b) }
fn @measure(@target:@qubit) @bit { }
"""
    )
    type_file = project / "src" / "hat_types" / "state.hat"
    type_file.write_text(
        """
type point { x:i64 y:i64 }
type status { ON OFF }
"""
    )

    result = update_project(project)

    assert result == {"source_files": 3, "docs_written": 3, "docs_removed": 0}
    math_doc = project / "docs" / "math.md"
    state_doc = project / "docs" / "hat_types" / "state.md"
    assert math_doc.exists()
    assert state_doc.exists()
    assert "## sum" in math_doc.read_text()
    assert "| a | i64 | classical |" in math_doc.read_text()
    assert "## @measure" in math_doc.read_text()
    assert "- Paradigm: quantum" in math_doc.read_text()
    assert "## point" in state_doc.read_text()
    assert "| x | i64 | classical |" in state_doc.read_text()
    assert "## status" in state_doc.read_text()
    assert "  - ON" in state_doc.read_text()

    math_doc.write_text(
        math_doc.read_text().replace("<!-- Add documentation here. -->", "Adds numbers.")
    )
    source_file.write_text("fn sum(left:i64 right:i64) i64 { ::add(left right) }\n")
    update_project(project)

    updated_math_doc = math_doc.read_text()
    assert "Adds numbers." in updated_math_doc
    assert "| left | i64 | classical |" in updated_math_doc
    assert "| a | i64 | classical |" not in updated_math_doc


def test_new_files_create_markdown_docs_with_replaced_suffix(tmp_path: Path) -> None:
    project = tmp_path / "demo"
    create_new_project(project)

    create_new_fn_file(project, "nested/logic")
    create_new_type_file(project, "custom")

    assert (project / "docs" / "main.md").exists()
    assert (project / "docs" / "nested" / "logic.md").exists()
    assert not (project / "docs" / "nested" / "logic.hat.md").exists()
    assert (project / "docs" / "hat_types" / "custom.md").exists()


def test_update_project_removes_orphan_docs(tmp_path: Path) -> None:
    project = tmp_path / "demo"
    create_new_project(project)
    orphan = project / "docs" / "old.md"
    orphan.write_text(
        "# old\n\n<!-- Generated by hat update; edit Documentation sections only. -->\n"
    )
    manual_doc = project / "docs" / "notes.md"
    manual_doc.write_text("# notes\n\nKeep me.\n")

    result = update_project(project)

    assert result["docs_removed"] == 1
    assert not orphan.exists()
    assert manual_doc.exists()
